"""Generate the system-design track map from metadata and the design-move registry.

Outputs (generated, never hand-edited):

* ``generated/diagrams/track/track-map.svg`` -- questions as nodes grouped by
  level, with an edge from the question that teaches a move in full to each
  question that reuses it, labelled with the number of moves shared. Only links
  with at least two shared moves are drawn.
* ``generated/catalogs/system-design-track.md`` -- a move-by-question matrix.

Usage: python -m tools.build_track_map
"""

from __future__ import annotations

import html
import re
from collections import defaultdict
from pathlib import Path
from typing import Dict, List

from tools.render_diagrams import graphviz_available, render_dot
from tools.validate import load_data

ROOT = Path(__file__).resolve().parents[1]


def _records(root: Path) -> List[Dict]:
    records = []
    for path in sorted((root / "content" / "system-design").glob("*/metadata.yaml")):
        metadata = load_data(path)
        if isinstance(metadata.get("track_order"), int):
            records.append(metadata)
    return sorted(records, key=lambda m: m["track_order"])


def _short(title: str, record: Dict | None = None) -> str:
    if record and record.get("short_title"):
        return str(record["short_title"])
    short = title.replace("Design a ", "").replace("Design an ", "")
    if " and " in short and len(short) > 30:
        short = short.split(" and ")[0]
    return short


def handbook_numbers(root: Path) -> Dict[str, str]:
    """Map handbook chapter IDs to their printed chapter numbers using INDEX.md."""
    index = root / "release1" / "handbook-markdown" / "INDEX.md"
    numbers: Dict[str, str] = {}
    if index.is_file():
        for line in index.read_text(encoding="utf-8").splitlines():
            match = re.match(r"^\|\s*(\d+)\s*\|.*`chapters/([a-z0-9-]+)/chapter\.md`", line)
            if match:
                numbers[match.group(2)] = match.group(1)
    return numbers


LEVELS = (("Foundation", lambda d: d <= 2), ("Intermediate", lambda d: d == 3), ("Advanced", lambda d: d >= 4))
MIN_SHARED_MOVES = 2


def level_of(record: Dict) -> str:
    difficulty = int(record.get("difficulty", 3))
    for name, test in LEVELS:
        if test(difficulty):
            return name
    return "Intermediate"


def build_dot(records: List[Dict], moves: Dict[str, Dict]) -> str:
    """One node per question listing the moves it teaches; an edge from the
    question that teaches a move in full to each question that reuses it,
    drawn only for links with at least MIN_SHARED_MOVES moves."""
    by_id = {r["id"]: r for r in records}
    edges: Dict[tuple, List[str]] = defaultdict(list)
    for record in records:
        for move_id in record.get("design_moves", {}).get("reuses", []):
            origin = moves.get(move_id, {}).get("introduced_in")
            if origin in by_id:
                edges[(origin, record["id"])].append(moves[move_id]["label"])
    lines = [
        "digraph track {",
        "  rankdir=TB; ranksep=0.4; nodesep=0.4;",
    ]
    for record in records:
        title = html.escape(_short(record["title"], record))
        introduced = [moves[m]["label"] for m in record.get("design_moves", {}).get("introduces", []) if m in moves]
        body = "\\l".join("· " + html.escape(label) for label in introduced) + "\\l"
        lines.append(
            f'  "{record["id"]}" [label="{title} · {level_of(record)}\\n{body}", role=new, fontsize=12];'
        )
    for (origin, target), labels in sorted(edges.items()):
        if len(labels) < MIN_SHARED_MOVES:
            continue
        lines.append(f'  "{origin}" -> "{target}" [label=" {len(labels)} moves"];')
    lines.append("}")
    return "\n".join(lines) + "\n"


def build_matrix(records: List[Dict], moves: Dict[str, Dict], numbers: Dict[str, str]) -> str:
    header = "| Design move | " + " | ".join(_short(r["title"], r) for r in records) + " | Handbook |"
    divider = "|---|" + "---|" * len(records) + "---|"
    rows = [
        "<!-- Generated by tools/build_track_map.py. Do not edit. -->",
        "",
        "● taught in full · ○ reused with a short explanation",
        "",
        header,
        divider,
    ]
    for move_id, move in moves.items():
        cells = []
        for record in records:
            dm = record.get("design_moves", {})
            cells.append("●" if move_id in dm.get("introduces", []) else "○" if move_id in dm.get("reuses", []) else "")
        handbook = ", ".join(f"Ch {numbers.get(h, h)}" for h in move.get("handbook", [])) or "—"
        rows.append(f"| {move['label']} | " + " | ".join(cells) + f" | {handbook} |")
    return "\n".join(rows) + "\n"


def main() -> int:
    records = _records(ROOT)
    registry = load_data(ROOT / "taxonomy" / "design-moves.yaml")
    moves = {move["id"]: move for move in registry["moves"]}
    catalog = ROOT / "generated" / "catalogs" / "system-design-track.md"
    catalog.parent.mkdir(parents=True, exist_ok=True)
    catalog.write_text(build_matrix(records, moves, handbook_numbers(ROOT)), encoding="utf-8")
    print(f"wrote {catalog.relative_to(ROOT)}")
    if graphviz_available():
        svg_path = ROOT / "generated" / "diagrams" / "track" / "track-map.svg"
        svg_path.parent.mkdir(parents=True, exist_ok=True)
        svg_path.write_text(render_dot(build_dot(records, moves)), encoding="utf-8")
        print(f"wrote {svg_path.relative_to(ROOT)}")
    else:
        print("skipped track-map.svg: Graphviz `dot` not installed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
